In [1]:
#cleaning data 
# handling missing values
import pandas as pd
df = pd.read_csv("raw_data.csv")

df.isnull()
df.isna()
df.isnull().sum()

df.dropna()
df.dropna(axis=1)

df.fillna(0)

age_mean = df["age"].mean()
df["age"].fillna(age_mean)

cleaned_data= df.copy()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
cleaned_data

df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [2]:
#handling the duplicates
df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()

df.drop_duplicates().copy
#df2 = df.copy
#df.drop_duplicates()

<bound method NDFrame.copy of     id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0>

In [3]:
#handling data types
df.dtypes
df2= df.copy()
df2 =df2.fillna(0) 
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes
df["gender"].str.lower()
df["name"].str.split(" ")
df["country"].str.contains("india",case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [4]:
#data type changing from obj to datetime
date_str =pd.Series([pd.to_datetime("2026-03-21")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [5]:
#feature eng 
df2 = df.copy();
df2["tax"] = df2["income"].apply(lambda x: "20%" if x>=60000 else "10%") #applying tax based on the condition

gender_map={"Male":"M","Female":"F","Unknown":"U"}
df2["gender"]=df2["gender"].map(gender_map) #maping the gender from Female --> F

df2=df2.assign(new_income=df2["income"]*1.1) #assigning new coln with 10 % inc in income

df2["country"]=df2["country"].replace("USA","United States") #replalcing usa --> United States

df2.columns =["ID","Name","Age","Country","Gender","Income","Tax","New_Income"] # renaming the colms from id --> Id
#df2.rename(columns={"Income":"Salary"}) # renamed the particular colmn Income --> Salary
df2.rename(index={1:"first"}) # rename the particular row 1 --> First 

df2.sort_values("Income") # sorting income in ascending ord
df2=df2.fillna(50)
df2.sort_values("Income",ascending =False) #sorting in descending ord
sorted_df =df2.sort_values(["Income","Age"]) # sorting basis of 2 columns (based on income , but if have same income checks age)

#reset
sorted_df.sort_index() #sorting the index (to its prev/starting phase)
sorted_df.reset_index()

#ranking
#sorted_df["Ranking"]=sorted_df["Income"].rank(ascending =False,method ="dense")

#reordering colmns 
sorted_df[["ID","Name","Age","Country","Gender","Income","New_Income","Tax"]]

    ID          Name   Age        Country Gender   Income  New_Income  Tax
4    4  Maria Garcia  34.0          Spain      F     50.0        50.0  10%
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0     49500.0  10%
3    3          Alex  50.0  United States      U  47000.0     51700.0  10%
5    5        Li Wei  27.0          China      M  51000.0     56100.0  10%
0    1      John Doe  29.0  United States      M  55000.0     60500.0  10%
1    1      John Doe  29.0  United States      M  55000.0     60500.0  10%
10  10   Emily Davis  31.0  United States     50  58000.0     63800.0  10%
8    8    Rachel Lee  29.0  United States      F  62000.0     68200.0  20%
2    2    Jane Smith  50.0         Canada      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0             50      M  68000.0     74800.0  20%
6    6            50  45.0          India      F  73000.0     80300.0  20%

In [6]:
sorted_df

    ID          Name   Age        Country Gender   Income  Tax  New_Income
4    4  Maria Garcia  34.0          Spain      F     50.0  10%        50.0
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%     49500.0
3    3          Alex  50.0  United States      U  47000.0  10%     51700.0
5    5        Li Wei  27.0          China      M  51000.0  10%     56100.0
0    1      John Doe  29.0  United States      M  55000.0  10%     60500.0
1    1      John Doe  29.0  United States      M  55000.0  10%     60500.0
10  10   Emily Davis  31.0  United States     50  58000.0  10%     63800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
2    2    Jane Smith  50.0         Canada      F  62000.0  20%     68200.0
7    7    Ahmed Khan  38.0             50      M  68000.0  20%     74800.0
6    6            50  45.0          India      F  73000.0  20%     80300.0

In [7]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [8]:
# changing dtype from obj to datetime
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtypes

dtype('<M8[ns]')

In [9]:
df2 = df.copy()

new_col_order =[col for col in df2.columns if col!="id"]+["id"]
print(new_col_order)
df2[new_col_order]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [10]:
df # orginal dat frame

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [11]:
df2= df.copy()
df2 =df2.drop_duplicates()
df2=df2.fillna(0)
df2 = df2.sort_values("income")
df2= df2.reset_index(drop =True)

df2.to_csv("sorted_data.csv")

In [12]:
df2

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0

In [36]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

df.groupby("gender")["income"].mean()
df.groupby("gender")["income"].min()
df.groupby("gender")["income"].max()

df.groupby("country")["income"].agg(["mean","min","max"])
df.groupby("country")["income"].aggregate(["mean","min","max"])

df.groupby("country")["income"].aggregate(avg_sal ="mean",min_sal ="min",max_sal="max")

df.groupby("country").agg({    # aggregate functions on diff colmns
    "income": "mean",
    "age":"mean"
})

df.groupby("country").agg({   # diff aggregate functions on diff colmns
    "income": "max",
    "age":"mean"
})

df.groupby("country").agg(    # changing the colm labels (max income & avg_age  of each country)
    max_sal =("income", "max"),
    avg_age=("age","mean")
)

         max_sal  avg_age
country
Canada   62000.0      NaN
China    51000.0     27.0
India    73000.0     45.0
Mexico   45000.0      NaN
Spain        NaN     34.0
USA      62000.0     29.5

In [24]:
 # melt and pivot
import pandas as pd
df =pd.DataFrame({
    "country":["USA","USA","India","India"],
    "year":[2020,2021,2020,2021],
    "sales":[100,120,90,110],
    "profit":[20,25,18,22],
})

##coverting wide to long -->using melt
melted_df =df.melt( 
    id_vars=["country","year"],
    value_vars=["sales","profit"],
    var_name="metrics",
    value_name="value"
)

##converting long to wide -->using pivot
original_df =melted_df.pivot(
    index=["country","year"],
    columns="metrics",
    values="value"
)

In [25]:
original_df

metrics       profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [26]:
melted_df

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22

In [27]:
df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      18
3   India  2021    110      22